apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: prism
  name: prism
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prism
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: prism
    spec:
      containers:
        - args:
            - mock
            - -h
            - 0.0.0.0
            - /tmp/api.oas3.yml
          image: stoplight/prism:4
          name: prism
          ports:
            - containerPort: 4010
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/api.oas3.yml
              name: prism-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: prism-claim0
          persistentVolumeClaim:
            claimName: prism-claim0
            readOnly: true
