apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: prism
  name: prism
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 4010
  selector:
    io.kompose.service: prism
